# named volumes:
volumes:
  world-db:

services:
  db:
    image: "mariadb:latest"
    volumes:
      # without volumes, data would be reset everytime
      # named volumes:
      # - world-db:/var/lib/mysql
      # local volumes
      #- ./conf/mysql:/etc/mysql/conf.d
      #- ./db/data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    environment:
      MARIADB_ROOT_PASSWORD: "supersecret"
      MARIADB_DATABASE: "world"
      MARIADB_USER: "example"
      MARIADB_PASSWORD: "example"

  web:
    # build specifies the location of a custom Dockerfile
    build: ./web
    depends_on:
      - db
    ports:
      - 80:80
    volumes:
      # without volumes, data would be reset everytime
      - ./conf/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./web/html:/var/www/html
    environment:
      MYSQL_HOST: "db"
      MYSQL_DATABASE: "world"
      MYSQL_USER: "example"
      MYSQL_PASSWORD: "example"

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: "db"
      PMA_USER: "example"
      PMA_PASSWORD: "example"